# Generated by Django 4.1.7 on 2023-03-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='no_of_quests',
            new_name='no_of_guests',
        ),
    ]
